/* GENERATED by scripts/generate.mjs — do not edit by hand. */
import type { MetadataRoute } from 'next';

export default function robots(): MetadataRoute.Robots {
  return {
    rules: { userAgent: '*', allow: '/', disallow: ['/thank-you'] },
    sitemap: 'https://www.vysmirasolutions.com/sitemap.xml',
    host: 'https://www.vysmirasolutions.com',
  };
}
