/* GENERATED by scripts/generate.mjs — do not edit by hand. */
import type { MetadataRoute } from 'next';

const ROUTES = [
  "/",
  "/about",
  "/about/leadership",
  "/about/approach",
  "/services",
  "/services/executive-search",
  "/services/permanent-recruitment",
  "/services/contract-staffing",
  "/services/rpo",
  "/services/talent-intelligence",
  "/services/hr-advisory",
  "/services/learning-development",
  "/industries",
  "/industries/semiconductor",
  "/industries/embedded-electronics",
  "/industries/automotive",
  "/industries/gcc",
  "/industries/information-technology",
  "/industries/manufacturing",
  "/industries/pharma-healthcare",
  "/insights",
  "/careers",
  "/careers/jobs",
  "/careers/jobs/senior-design-verification-engineer-bengaluru",
  "/careers/jobs/engineering-manager-adas-pune",
  "/careers/jobs/site-hr-head-gcc-bengaluru",
  "/insights/why-your-niche-engineering-role-has-been-open-six-months",
  "/careers/submit-cv",
  "/contact",
  "/privacy-policy",
  "/terms-of-use",
  "/cookie-policy"
];

export default function sitemap(): MetadataRoute.Sitemap {
  const lastModified = new Date();
  return ROUTES.map((route) => ({
    url: `https://www.vysmirasolutions.com${route === '/' ? '' : route}`,
    lastModified,
    changeFrequency: route.startsWith('/careers/jobs/') ? 'weekly' : 'monthly',
    priority: route === '/' ? 1 : route.split('/').length > 2 ? 0.6 : 0.8,
  }));
}
