/* Regenerates the Next.js app from the single-file preview build.
   Source of truth stays vysmira-preview.html — re-run `npm run generate`
   after any edit to it. */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SRC = path.resolve(ROOT, '..', 'vysmira-preview.html');
const APP = path.join(ROOT, 'app');
const PUB = path.join(ROOT, 'public');
const CMP = path.join(ROOT, 'components');

const src = fs.readFileSync(SRC, 'utf8');
const slice = (from, to) => src.slice(src.indexOf(from), src.indexOf(to) + to.length);

/* ---- 1. Assets: pull inlined base64 PNGs out into public/ --------------- */
const assets = new Map(); // base64 -> public path
function externalise(html) {
  return html.replace(/data:image\/(png|jpeg|jpg|webp|gif);base64,([A-Za-z0-9+/=]+)/g, (_m, type, b64) => {
    if (!assets.has(b64)) {
      const ext = type === 'jpeg' ? 'jpg' : type;
      const file = `/img/asset-${assets.size + 1}.${ext}`;
      assets.set(b64, file);
      fs.mkdirSync(path.join(PUB, 'img'), { recursive: true });
      fs.writeFileSync(path.join(PUB, 'img', path.basename(file)), Buffer.from(b64, 'base64'));
    }
    return assets.get(b64);
  });
}

/* ---- 2. Hash routes -> real Next.js paths ------------------------------ */
// Image paths are relative in the preview build so it still works over
// file://. Next serves the same files from /public, and a relative path would
// otherwise resolve against a nested route (/careers/img/... -> 404).
const absolutiseUrls = (s) => s.replace(/url\((["']?)(?!\/|https?:|data:)/g, 'url($1/');

const rewrite = (html) =>
  absolutiseUrls(externalise(html))
    .replace(/href="#\/"/g, 'href="/"')
    .replace(/href="#\/([^"]*)"/g, 'href="/$1"');

/* ---- 3. Chrome: header, mobile nav, footer, sticky CTA ----------------- */
const headerHtml = rewrite(slice('<div class="utility">', '</header>'));
const mobileNavHtml = rewrite(
  src.slice(src.indexOf('<div class="mobile-nav" id="mobile-nav">'), src.indexOf('<main id="main">')).trim()
);
const footerHtml = rewrite(slice('<footer class="site-footer">', '</footer>'));
const ctaHtml = rewrite(
  src.slice(src.indexOf('<div class="mobile-cta">'), src.indexOf('<div id="preview-banner"')).trim()
);

fs.mkdirSync(CMP, { recursive: true });
fs.writeFileSync(
  path.join(CMP, 'chrome.ts'),
  '/* GENERATED by scripts/generate.mjs — do not edit by hand. */\n' +
    `export const headerHtml = ${JSON.stringify(headerHtml)};\n\n` +
    `export const mobileNavHtml = ${JSON.stringify(mobileNavHtml)};\n\n` +
    `export const footerHtml = ${JSON.stringify(footerHtml)};\n\n` +
    `export const ctaHtml = ${JSON.stringify(ctaHtml)};\n`
);

/* ---- 4. Design system -> app/globals.css ------------------------------- */
const css = absolutiseUrls(/<style>([\s\S]*?)<\/style>/.exec(src)[1].trim());
fs.writeFileSync(path.join(APP, 'globals.css'), css + '\n');

// Copy any hand-placed art next to the preview build into public/.
const srcImgDir = path.resolve(SRC, '..', 'img');
let copied = 0;
if (fs.existsSync(srcImgDir)) {
  fs.mkdirSync(path.join(PUB, 'img'), { recursive: true });
  for (const file of fs.readdirSync(srcImgDir)) {
    fs.copyFileSync(path.join(srcImgDir, file), path.join(PUB, 'img', file));
    copied++;
  }
}

/* ---- 5. Behaviour layer -> public/site.js ------------------------------ */
const jsStart = src.lastIndexOf('<script>', src.indexOf('/* VYSMIRA Solutions')) + '<script>'.length;
let js = src.slice(jsStart, src.indexOf('</script>', jsStart));

// The single-file router re-ran the whole boot() on every hash change. Under
// Next the header/nav survive navigation, so re-binding those would stack
// duplicate listeners. Split boot into once-only chrome + per-page work.
js = js.replace(
  /function boot\(\) \{[\s\S]*?\n  \}/,
  `function boot() {
    if (!window.__vysChromeBooted) {
      window.__vysChromeBooted = true;
      initHeader();
      initMegaMenus();
      initMobileNav();
      initMobileCta();
    }
    initPage();
  }

  function initPage() {
    initReveal();
    initCounters();
    initForms();
    markCurrent();
  }`
);
js = js.replace('window.VYSMIRA = { boot: boot };', 'window.VYSMIRA = { boot: boot, initPage: initPage };');

if (!js.includes('initPage: initPage')) throw new Error('behaviour script patch failed');
fs.writeFileSync(path.join(PUB, 'site.js'), js.trim() + '\n');

/* ---- 6. Structured data ------------------------------------------------ */
const ldjson = /<script type="application\/ld\+json">([\s\S]*?)<\/script>/.exec(src)[1].trim();
fs.writeFileSync(path.join(CMP, 'ldjson.ts'), `export const ldJson = ${JSON.stringify(ldjson)};\n`);

/* ---- 7. Views -> one route each ---------------------------------------- */
const viewRe = /<div class="view" id="v-([^"]+)" data-nav="([^"]*)" data-title="([^"]*)"[^>]*>/g;
const mainEnd = src.indexOf('</main>');
const views = [];
let m;
while ((m = viewRe.exec(src))) {
  views.push({
    route: m[1],
    nav: m[2],
    title: decodeEntities(m[3]),
    tagStart: m.index,
    start: m.index + m[0].length,
  });
}
views.forEach((v, i) => {
  const end = i + 1 < views.length ? views[i + 1].tagStart : mainEnd;
  // Each view block closes with the wrapper </div> we are replacing with <PageBody>.
  v.html = rewrite(src.slice(v.start, end).trim().replace(/<\/div>$/, '').trim());
});

function decodeEntities(s) {
  return s
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&middot;/g, '·')
    .replace(/&mdash;/g, '—')
    .replace(/&ndash;/g, '–');
}

// Wipe previously generated routes so deletions in the source propagate.
for (const entry of fs.readdirSync(APP, { withFileTypes: true })) {
  if (entry.isDirectory()) fs.rmSync(path.join(APP, entry.name), { recursive: true, force: true });
}

let pages = 0;
for (const v of views) {
  const isHome = v.route === 'home';
  const is404 = v.route === '404';
  const dir = isHome || is404 ? APP : path.join(APP, ...v.route.split('/'));
  fs.mkdirSync(dir, { recursive: true });

  const body =
    '/* GENERATED by scripts/generate.mjs — do not edit by hand. */\n' +
    (is404 ? '' : "import type { Metadata } from 'next';\n") +
    "import PageBody from '@/components/PageBody';\n\n" +
    (is404 ? '' : `export const metadata: Metadata = { title: ${JSON.stringify(v.title)} };\n\n`) +
    `const html = ${JSON.stringify(v.html)};\n\n` +
    `export default function ${is404 ? 'NotFound' : 'Page'}() {\n` +
    `  return <PageBody nav=${JSON.stringify(v.nav)} html={html} />;\n` +
    '}\n';

  fs.writeFileSync(path.join(dir, is404 ? 'not-found.tsx' : 'page.tsx'), body);
  pages++;
}

console.log(
  `generated ${pages} routes, ${assets.size} extracted + ${copied} copied image assets, ` +
    `${(css.length / 1024) | 0}KB css, ${(js.length / 1024) | 0}KB js`
);
