/* Regenerates the Next.js app from the single-file preview build.
   Source of truth stays vysmira-preview.html — re-run `npm run generate`
   after any edit to it. */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SRC = path.resolve(ROOT, '..', 'vysmira-preview.html');
const APP = path.join(ROOT, 'app');
const PUB = path.join(ROOT, 'public');
const CMP = path.join(ROOT, 'components');

const src = fs.readFileSync(SRC, 'utf8');
const slice = (from, to) => src.slice(src.indexOf(from), src.indexOf(to) + to.length);

// public/img is fully derived — extracted base64 assets plus whatever sits in
// ../img. Clear it first so files removed from the source (e.g. originals
// replaced by .webp) don't linger in the deploy.
const PUB_IMG = path.join(PUB, 'img');
fs.rmSync(PUB_IMG, { recursive: true, force: true });
fs.mkdirSync(PUB_IMG, { recursive: true });

/* ---- 1. Assets: pull inlined base64 PNGs out into public/ --------------- */
const assets = new Map(); // base64 -> public path
function externalise(html) {
  return html.replace(/data:image\/(png|jpeg|jpg|webp|gif);base64,([A-Za-z0-9+/=]+)/g, (_m, type, b64) => {
    if (!assets.has(b64)) {
      const ext = type === 'jpeg' ? 'jpg' : type;
      const file = `/img/asset-${assets.size + 1}.${ext}`;
      assets.set(b64, file);
      fs.mkdirSync(path.join(PUB, 'img'), { recursive: true });
      fs.writeFileSync(path.join(PUB, 'img', path.basename(file)), Buffer.from(b64, 'base64'));
    }
    return assets.get(b64);
  });
}

/* ---- 2. Hash routes -> real Next.js paths ------------------------------ */
// Image paths are relative in the preview build so it still works over
// file://. Next serves the same files from /public, and a relative path would
// otherwise resolve against a nested route (/careers/img/... -> 404).
const absolutiseUrls = (s) => s.replace(/url\((["']?)(?!\/|https?:|data:)/g, 'url($1/');

const rewrite = (html) =>
  absolutiseUrls(externalise(html))
    .replace(/(?<![\w-])(src|srcset|poster)="(?!\/|https?:|data:|#)/g, '$1="/')
    .replace(/href="#\/"/g, 'href="/"')
    .replace(/href="#\/([^"]*)"/g, 'href="/$1"');

/* ---- 3. Chrome: header, mobile nav, footer, sticky CTA ----------------- */
const headerHtml = rewrite(slice('<div class="utility">', '</header>'));
const mobileNavHtml = rewrite(
  src.slice(src.indexOf('<div class="mobile-nav" id="mobile-nav">'), src.indexOf('<main id="main">')).trim()
);
const footerHtml = rewrite(slice('<footer class="site-footer">', '</footer>'));
const ctaHtml = rewrite(
  src.slice(src.indexOf('<div class="mobile-cta">'), src.indexOf('<div id="preview-banner"')).trim()
);

fs.mkdirSync(CMP, { recursive: true });
fs.writeFileSync(
  path.join(CMP, 'chrome.ts'),
  '/* GENERATED by scripts/generate.mjs — do not edit by hand. */\n' +
    `export const headerHtml = ${JSON.stringify(headerHtml)};\n\n` +
    `export const mobileNavHtml = ${JSON.stringify(mobileNavHtml)};\n\n` +
    `export const footerHtml = ${JSON.stringify(footerHtml)};\n\n` +
    `export const ctaHtml = ${JSON.stringify(ctaHtml)};\n`
);

/* ---- 4. Design system -> app/globals.css ------------------------------- */
const css = absolutiseUrls(/<style>([\s\S]*?)<\/style>/.exec(src)[1].trim());
fs.writeFileSync(path.join(APP, 'globals.css'), css + '\n');

// Copy any hand-placed art next to the preview build into public/.
const srcImgDir = path.resolve(SRC, '..', 'img');
let copied = 0;
if (fs.existsSync(srcImgDir)) {
  fs.mkdirSync(path.join(PUB, 'img'), { recursive: true });
  for (const file of fs.readdirSync(srcImgDir)) {
    fs.copyFileSync(path.join(srcImgDir, file), path.join(PUB, 'img', file));
    copied++;
  }
}

/* ---- 5. Behaviour layer -> public/site.js ------------------------------ */
const jsStart = src.lastIndexOf('<script>', src.indexOf('/* VYSMIRA Solutions')) + '<script>'.length;
let js = src.slice(jsStart, src.indexOf('</script>', jsStart));

// The single-file router re-ran the whole boot() on every hash change. Under
// Next the header/nav survive navigation, so re-binding those would stack
// duplicate listeners. Split boot into once-only chrome + per-page work.
//
// The two lists are derived from boot()'s actual body rather than hardcoded, so
// anything added to boot() in the preview build flows through automatically.
const CHROME_INITS = ['initHeader', 'initMegaMenus', 'initMobileNav', 'initMobileCta'];
const bootBody = /function boot\(\) \{([\s\S]*?)\n  \}/.exec(js);
if (!bootBody) throw new Error('could not locate boot() in the behaviour script');

const calls = bootBody[1]
  .split('\n')
  .map((l) => l.trim())
  .filter((l) => /^init[A-Za-z]*\(\);$|^mark[A-Za-z]*\(\);$/.test(l));
const chromeCalls = calls.filter((c) => CHROME_INITS.some((n) => c === n + '();'));
const pageCalls = calls.filter((c) => !chromeCalls.includes(c));

const missing = CHROME_INITS.filter((n) => !chromeCalls.includes(n + '();'));
if (missing.length) throw new Error(`boot() no longer calls: ${missing.join(', ')}`);
if (!pageCalls.length) throw new Error('boot() has no page-scoped calls left to run per route');

const indent = (list, pad) => list.map((c) => pad + c).join('\n');
js = js.replace(
  /function boot\(\) \{[\s\S]*?\n  \}/,
  `function boot() {
    if (!window.__vysChromeBooted) {
      window.__vysChromeBooted = true;
${indent(chromeCalls, '      ')}
    }
    initPage();
  }

  function initPage() {
${indent(pageCalls, '    ')}
  }`
);
js = js.replace('window.VYSMIRA = { boot: boot };', 'window.VYSMIRA = { boot: boot, initPage: initPage };');

if (!js.includes('initPage: initPage')) throw new Error('behaviour script patch failed');
fs.writeFileSync(path.join(PUB, 'site.js'), js.trim() + '\n');

/* ---- 6. Structured data ------------------------------------------------ */
const ldjson = /<script type="application\/ld\+json">([\s\S]*?)<\/script>/.exec(src)[1].trim();
fs.writeFileSync(path.join(CMP, 'ldjson.ts'), `export const ldJson = ${JSON.stringify(ldjson)};\n`);

/* ---- 7. Views -> one route each ---------------------------------------- */
const viewRe = /<div class="view" id="v-([^"]+)" data-nav="([^"]*)" data-title="([^"]*)"([^>]*)>/g;
const mainEnd = src.indexOf('</main>');
const views = [];
let m;
while ((m = viewRe.exec(src))) {
  views.push({
    route: m[1],
    nav: m[2],
    title: decodeEntities(m[3]),
    posted: (/data-posted="([^"]+)"/.exec(m[4]) || [])[1] || null,
    validThrough: (/data-valid-through="([^"]+)"/.exec(m[4]) || [])[1] || null,
    tagStart: m.index,
    start: m.index + m[0].length,
  });
}
views.forEach((v, i) => {
  const end = i + 1 < views.length ? views[i + 1].tagStart : mainEnd;
  // Each view block closes with the wrapper </div> we are replacing with <PageBody>.
  v.html = rewrite(src.slice(v.start, end).trim().replace(/<\/div>$/, '').trim());
});

/* ---- 7a. SEO: descriptions and breadcrumbs derived from each view ------- */
const SITE = 'https://www.vysmirasolutions.com';
const OG_IMAGE = '/img/og-default.png';

// Pages that exist for users mid-flow, not for search results.
const NOINDEX = new Set(['thank-you', '404']);

const stripTags = (html) =>
  decodeEntities(
    html
      .replace(/<[^>]+>/g, ' ')
      .replace(/\s+/g, ' ')
      .trim()
  );

// Google renders roughly 155 characters; cut on a word boundary, never mid-word.
function truncate(text, limit = 155) {
  if (text.length <= limit) return text;
  const cut = text.slice(0, limit + 1);
  const lastSpace = cut.lastIndexOf(' ');
  return cut.slice(0, lastSpace > 60 ? lastSpace : limit).replace(/[,;:\s]+$/, '') + '…';
}

// The lede under each h1 is already a one-sentence summary of the page — far
// better copy than anything generated, and it stays in sync with the content.
function extractDescription(html, fallback) {
  // Only look inside the opening hero/page-hero block. Interior sections also
  // use .lede, and picking one of those would describe a mid-page section
  // rather than the page itself.
  const firstSection = html.slice(0, html.indexOf('</section>') + 1) || html;
  const pick = (scope) =>
    /class="lede"[^>]*>([\s\S]*?)<\/p>/.exec(scope) || /class="hero__sub"[^>]*>([\s\S]*?)<\/p>/.exec(scope);

  const match = pick(firstSection) || pick(html);
  const text = match ? stripTags(match[1]) : '';
  return text ? truncate(text) : fallback;
}

// Each interior page already renders a visible breadcrumb; mirror it as
// BreadcrumbList so the trail shows in search results too.
function extractBreadcrumb(html, route) {
  const nav = /<nav class="breadcrumb"[^>]*>([\s\S]*?)<\/nav>/.exec(html);
  if (!nav) return null;

  // Test the whole <li> tag, not its contents — the "/" separators carry
  // class="sep" on the element itself.
  const items = [...nav[1].matchAll(/<li[^>]*>[\s\S]*?<\/li>/g)]
    .map((m) => m[0])
    .filter((li) => !/class="sep"/.test(li));
  if (items.length < 2) return null;

  const crumbs = items.map((li) => {
    // Hrefs are already rewritten to real paths by this point.
    const href = /href="(\/[^"]*)"/.exec(li);
    return { name: stripTags(li), path: href ? href[1] : null };
  });
  // The final crumb is the current page, which the markup renders unlinked.
  crumbs[crumbs.length - 1].path = `/${route}`;

  return JSON.stringify({
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: crumbs.map((c, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      name: c.name,
      item: SITE + (c.path === '/' ? '' : c.path ?? ''),
    })),
  });
}

// Google Jobs requires a real datePosted. Rather than invent one, each job view
// must declare data-posted="YYYY-MM-DD" (optionally data-valid-through) in the
// preview build; without it we emit no JobPosting rather than bad structured data.
function extractJobPosting(html, route, title, description, posted, validThrough) {
  if (!posted) return null;

  const facts = {};
  for (const m of html.matchAll(/<span class="mark">([^<]+)<\/span>([^<]*)</g)) {
    facts[stripTags(m[1]).toUpperCase()] = stripTags(m[2]);
  }
  const location = facts.LOCATION || 'Bengaluru, Karnataka';
  const [city, region] = location.split(',').map((x) => x.trim());

  const EMPLOYMENT = { Permanent: 'FULL_TIME', Contract: 'CONTRACTOR', 'Full-time': 'FULL_TIME' };

  return JSON.stringify({
    '@context': 'https://schema.org',
    '@type': 'JobPosting',
    title,
    description,
    datePosted: posted,
    ...(validThrough ? { validThrough } : {}),
    employmentType: EMPLOYMENT[facts.TYPE] || 'FULL_TIME',
    ...(facts.REFERENCE ? { identifier: { '@type': 'PropertyValue', name: 'VYSMIRA Solutions', value: facts.REFERENCE } } : {}),
    hiringOrganization: {
      '@type': 'Organization',
      name: 'VYSMIRA Solutions',
      sameAs: SITE,
    },
    jobLocation: {
      '@type': 'Place',
      address: {
        '@type': 'PostalAddress',
        addressLocality: city || 'Bengaluru',
        addressRegion: region || 'Karnataka',
        addressCountry: 'IN',
      },
    },
    directApply: false,
    url: `${SITE}/${route}`,
  });
}

function decodeEntities(s) {
  return s
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&middot;/g, '·')
    .replace(/&mdash;/g, '—')
    .replace(/&ndash;/g, '–');
}

// Wipe previously generated routes so deletions in the source propagate.
for (const entry of fs.readdirSync(APP, { withFileTypes: true })) {
  if (entry.isDirectory()) fs.rmSync(path.join(APP, entry.name), { recursive: true, force: true });
}

const SITE_DESCRIPTION =
  'Specialist recruitment and human capital consulting for semiconductor, embedded, automotive and engineering organisations in India.';

let pages = 0;
const indexable = [];
const missingJobDates = [];
for (const v of views) {
  const isHome = v.route === 'home';
  const is404 = v.route === '404';
  const dir = isHome || is404 ? APP : path.join(APP, ...v.route.split('/'));
  fs.mkdirSync(dir, { recursive: true });

  const urlPath = isHome ? '/' : `/${v.route}`;
  const description = extractDescription(v.html, SITE_DESCRIPTION);
  const noindex = NOINDEX.has(v.route);
  const breadcrumb = is404 ? null : extractBreadcrumb(v.html, v.route);

  const isJob = v.route.startsWith('careers/jobs/') && v.route.split('/').length > 2;
  const h1 = /<h1[^>]*>([\s\S]*?)<\/h1>/.exec(v.html);
  const jobPosting = isJob
    ? extractJobPosting(v.html, v.route, h1 ? stripTags(h1[1]) : v.title, description, v.posted, v.validThrough)
    : null;
  if (isJob && !jobPosting) missingJobDates.push(v.route);

  const ld = [breadcrumb, jobPosting].filter(Boolean);

  if (!noindex) indexable.push(urlPath);

  const metadata = {
    title: v.title,
    description,
    alternates: { canonical: urlPath },
    openGraph: {
      title: v.title,
      description,
      url: urlPath,
      siteName: 'VYSMIRA Solutions',
      locale: 'en_IN',
      type: isJob || v.route.startsWith('insights/') ? 'article' : 'website',
      images: [{ url: OG_IMAGE, width: 1200, height: 630, alt: 'VYSMIRA Solutions' }],
    },
    twitter: {
      card: 'summary_large_image',
      title: v.title,
      description,
      images: [OG_IMAGE],
    },
    ...(noindex ? { robots: { index: false, follow: true } } : {}),
  };

  const body =
    '/* GENERATED by scripts/generate.mjs — do not edit by hand. */\n' +
    (is404 ? '' : "import type { Metadata } from 'next';\n") +
    "import PageBody from '@/components/PageBody';\n\n" +
    (is404 ? '' : `export const metadata: Metadata = ${JSON.stringify(metadata, null, 2)};\n\n`) +
    `const html = ${JSON.stringify(v.html)};\n\n` +
    (ld.length ? `const jsonLd = ${JSON.stringify(ld, null, 2)};\n\n` : '') +
    `export default function ${is404 ? 'NotFound' : 'Page'}() {\n` +
    (ld.length
      ? '  return (\n' +
        '    <>\n' +
        '      {jsonLd.map((block, i) => (\n' +
        '        <script key={i} type="application/ld+json" dangerouslySetInnerHTML={{ __html: block }} />\n' +
        '      ))}\n' +
        `      <PageBody nav=${JSON.stringify(v.nav)} html={html} />\n` +
        '    </>\n' +
        '  );\n'
      : `  return <PageBody nav=${JSON.stringify(v.nav)} html={html} />;\n`) +
    '}\n';

  fs.writeFileSync(path.join(dir, is404 ? 'not-found.tsx' : 'page.tsx'), body);
  pages++;
}

/* ---- 8. sitemap.xml and robots.txt ------------------------------------- */
fs.writeFileSync(
  path.join(APP, 'sitemap.ts'),
  '/* GENERATED by scripts/generate.mjs — do not edit by hand. */\n' +
    "import type { MetadataRoute } from 'next';\n\n" +
    `const ROUTES = ${JSON.stringify(indexable, null, 2)};\n\n` +
    'export default function sitemap(): MetadataRoute.Sitemap {\n' +
    '  const lastModified = new Date();\n' +
    '  return ROUTES.map((route) => ({\n' +
    `    url: \`${SITE}\${route === '/' ? '' : route}\`,\n` +
    '    lastModified,\n' +
    "    changeFrequency: route.startsWith('/careers/jobs/') ? 'weekly' : 'monthly',\n" +
    "    priority: route === '/' ? 1 : route.split('/').length > 2 ? 0.6 : 0.8,\n" +
    '  }));\n' +
    '}\n'
);

fs.writeFileSync(
  path.join(APP, 'robots.ts'),
  '/* GENERATED by scripts/generate.mjs — do not edit by hand. */\n' +
    "import type { MetadataRoute } from 'next';\n\n" +
    'export default function robots(): MetadataRoute.Robots {\n' +
    '  return {\n' +
    "    rules: { userAgent: '*', allow: '/', disallow: ['/thank-you'] },\n" +
    `    sitemap: '${SITE}/sitemap.xml',\n` +
    `    host: '${SITE}',\n` +
    '  };\n' +
    '}\n'
);

if (missingJobDates.length) {
  console.warn('  ! no JobPosting emitted for ' + missingJobDates.length + ' job page(s).');
  console.warn('    Add data-posted="YYYY-MM-DD" to these views in vysmira-preview.html:');
  for (const r of missingJobDates) console.warn('      ' + r);
}

console.log(
  `generated ${pages} routes, ${assets.size} extracted + ${copied} copied image assets, ` +
    `${(css.length / 1024) | 0}KB css, ${(js.length / 1024) | 0}KB js`
);
